### PR TITLE
Add optional wait parameter where needed

### LINKED ISSUE #23: Support optional wait parameter
We want to use this package to deploy from command line in ci, so we have to do multiple steps in the right order.
To do this we need to wait for everything ;)

We need to bump the sdk to v2 for that (https://github.com/svenluijten/forge-cli/pull/20)

We will add `$wait` as an optional parameter where possible and use the default value from the sdk itself.

### PR DESCRIPTION
**Pull request by thoresuenert**
closes #23

### CODE REVIEW

**Comment by svenluijten** [comment]
Thanks for this! I'll take a look when I get some time (should be this weekend), as well as set up Travis to properly run the (limited) tests we have 🙂

**Comment by thoresuenert** [comment]
There is a problem with the Certificates:install command, the new sdk added a data payload array.
The sdk and the docs are confusing at this point.

What do we want to achieve with`install:certificate` command?
from the arguments it looks like we dont want to install a certificate, we want to clone an existing one instead.

From the docs: 

```
HTTP Request

POST /api/v1/servers/{serverId}/sites/{siteId}/certificates/{id}/install



    Payload

{
    "certificate": "certificate content",
    "add_intermediates": false
}
```

**Comment by thoresuenert** [comment]
@svenluijten dont waste anytime on this PR.

I had a dive into laravel core how to test the commands etc.

The last commit should be the right way to test and build optional none value flags like `wait` should be.

Pleas provide feedback which way to go and i will clean this PR.

**Comment by svenluijten** [comment]
Yeah that last commit is how I would do it as well. The tests still feel quite "fragile", because we're mocking third party dependencies ("don't mock what you don't own"), but writing a wrapper around all those objects feels a bit excessive for now. 

All in all, LGTM! Let me know if you need any more pointers 🙂

**Comment by thoresuenert** [comment]
moved the certificate question into the following issue #27

**Pull request closed without merging**
